### ISSUE TITLE
Language update and documentation improvement

### ISSUE THREAD

**Issue by moesio-f** [Gabriel-AB/optfuncs#5]
Translate comments, docstrings, and other documentation/codes to English. 
Create README and improve docstring.

# Tasks
- [ ] Create README
- [x] Translate and improve documentation in `core.py`
- [x] Translate and improve documentation in `functions_test.py`
- [x] Translate and improve documentation in `numpy_functions.py`
- [x] Translate and improve documentation in `tensorflow_functions.py`
